stages:
  load_data:
    cmd: python src\load_data.py --config=params.yaml
    deps:
      - src\get_data.py
      - src\load_data.py
      - data_given\Mall_Customers.csv
    outs:
      - data\raw\Mall_Customers.csv

  process_data:
    cmd: python src\process_data.py --config=params.yaml
    deps:
      - src\process_data.py
      - data\raw\Mall_Customers.csv
    outs:
      - data\processed\Mall_Customers.csv

  train_and_evaluate:
    cmd: python src\train_and_evaluate.py --config=params.yaml
    deps:
      - data\processed\Mall_Customers.csv
      - src\train_and_evaluate.py
    params:
      - estimators.KMeans.params.n_clusters
    metrics:
      - report\scores.json:
          cache: false
      - report\params.json:
          cache: false      
    outs:
      - saved_models\model.joblib
      - prediction_service/model/model.joblib
