base:
  project: Clustering-on-mall customers data
  random_state: 42

data_source:
  s3_source: data_given\Mall_Customers.csv

load_data:
  raw_dataset_csv: data\raw\Mall_Customers.csv

process_data: data\processed\Mall_Customers.csv

estimators:
  KMeans:
    params:
      n_clusters: 12

model_dir: saved_models

reports:
  scores: report\scores.json
  params: report\params.json

webapp_final_model_dir: prediction_service\model\model.joblib

trained_data: data\trained\Mall_Customers.csv
