base:
  project: Clustering-on-stocksData
  random_state: 42

data_source:
  s3_source: data_given\stocks.csv

load_data:
  raw_dataset_csv: data\raw\stocks.csv

process_data: data\processed\stocks.csv  

estimators:
  HHDBSCAN:
  params:
    min_cluster_size: 60
    min_samples: 1
    cluster_selection_epsilon: 2
  
model_dir: saved_models

